name: example-basic
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  basic-ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/basic
          build: npx cypress info
