name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests (6 workers)
        run: yarn pw:6
      - name: Store time taken (6 workers)
        id: store-time-taken-6w
        run: node read-test.js
      - uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 6d4aa86c65259c0b1e1d61d644c88c84
          filename: pw-6.json
          label: Playwright (6 workers, w/o startup)
          message: ${{ steps.store-time-taken-6w.outputs.PLAYWRIGHT_TIME_TAKEN }}
          color: brightgreen
      - name: Run Playwright tests (1 worker)
        run: yarn pw:1
      - name: Store time taken (1 worker)
        id: store-time-taken-1w
        run: node read-test.js
      - uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 6d4aa86c65259c0b1e1d61d644c88c84
          filename: pw-1.json
          label: Playwright (1 worker, w/o startup)
          message: ${{ steps.store-time-taken-1w.outputs.PLAYWRIGHT_TIME_TAKEN }}
          color: green
